## Exercício

Você é um analista de RH e tem os salários de todos os funcionários da sua empresa em um array NumPy. Seu trabalho é identificar quantos funcionários ganham acima da média. Use o seguinte array para sua análise: `salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])`.

In [1]:
import numpy as np

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])


In [7]:
media_salario = np.mean(salarios)
acima_media = salarios[salarios>media_salario]
print(np.where(salarios > media_salario))
print(acima_media)
print(np.sum(salarios>media_salario))
print(len(acima_media))

(array([2, 3, 5, 7, 8]),)
[3500 4000 4500 3800 4800]
5
5


In [9]:
print(np.count_nonzero(salarios>media_salario))

5


In [13]:
print(np.unique(salarios>media_salario))
print(np.unique(salarios))

[False  True]
[2000 2500 3000 3500 3800 4000 4500 4800]


In [14]:
print(np.unique(salarios>media_salario,return_counts=True))


(array([False,  True]), array([4, 5]))


In [16]:
valores_unicos,contagem = np.unique(salarios>media_salario,return_counts=True)
print(valores_unicos)
print(contagem)

[False  True]
[4 5]


In [20]:
rng = np.random.default_rng(seed=42)

salarios_gerados = rng.integers(low=np.min(salarios),high=np.max(salarios),size=20)
print(salarios_gerados)

[2249 4167 3832 3228 3212 4404 2240 3952 2564 2263 3474 4731 4060 4131
 4008 4200 3437 2358 4351 3261]


In [21]:
rng = np.random.default_rng(seed=42)
salarios_gerados = rng.integers(low=np.min(salarios),high=np.max(salarios),size=20,endpoint=True)
print(salarios_gerados)

[2249 4167 3833 3229 3212 4404 2240 3953 2564 2263 3474 4732 4060 4131
 4009 4201 3437 2358 4352 3261]
